### ISSUE TITLE
[Feature Request] CS:S Support

### ISSUE THREAD

**Issue by notfoundname** [Mikusch/source-vehicles#17]
I don't know if that's a good feature request but it would be cool if this plugin will also work for counter strike source or any other game that also has broken prop_vehicle_driveable
https://forums.alliedmods.net/showpost.php?p=1765007&postcount=662 maybe this will help

**Comment by Mikusch** [comment]
This should actually be possible to do without any code changes, although it will require a lot of work since I'm pretty sure most signatures and virtual offsets won't match up with the CS:S server binary. I probably won't be able to take a look at this anytime soon but others are free to investigate.

If support were to be added a rebranding of the plugin with a new major version would be required.

**Comment by Mikusch** [comment]
I did a little digging, and theoretically it should be possible to do in a single evening (if you're dedicated):

### Possible code changes
We set the `tf_allow_player_use` convar on plugin start, and reset the value on plugin end. This might need a change.
Additionally, the `voicemenu` hook to allow MEDIC! calls to enter into vehicles. Maybe this should be made more modular to allow putting any command in there.

### Required gamedata updates
**Signatures:**
CPlayerMove::SetupMove
CBasePlayer::CanEnterVehicle
CBaseAnimating::GetAttachmentLocal

**Virtual offsets:**
CBaseAnimating::StudioFrameAdvance
CBasePlayer::GetInVehicle
CBasePlayer::LeaveVehicle

**Comment by Mikusch** [comment]
@notfoundname Good news, I had some spare time and managed to port the plugin over to CS:S. It will require some polish, but it looks good so far.

![image](https://user-images.githubusercontent.com/25514044/121618429-08063980-ca67-11eb-8b32-a94c58e37808.png)

**Comment by notfoundname** [comment]
om you really did it, thank you so much!

**Comment by Mikusch** [comment]
Closing this, as it's implemented with #19. Thanks for the suggestion!
